import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const initialServices = [
  { id: 'gel', name: 'Gel color semipermanente', price: 60, duration: 120 },
  { id: 'rubber', name: 'Rubber', price: 70, duration: 150 },
  { id: 'soft', name: 'Soft gel', price: 100, duration: 180 },
  { id: 'polygel', name: 'Polygel sobre uña natural', price: 110, duration: 180 },
  { id: 'acrilica', name: 'Acrílica con tips', price: 130, duration: 210 },
  { id: 'builder', name: 'Builder sobre uña natural', price: 85, duration: 150 },
  { id: 'mani', name: 'Manicura (limpieza y limado)', price: 35, duration: 60 },
  { id: 'pedi', name: 'Pedicura en seco', price: 50, duration: 75 },
  { id: 'spa', name: 'Pedicura spa', price: 80, duration: 105 }
];
const extras = [{ id: 'retiroHaru', name: 'Retiro de Haru', price: 20 }, { id: 'retiroExterno', name: 'Retiro de otro salón', price: 30 }, { id: 'diseno', name: 'Diseño personalizado', price: 25 }];
const steps = ['Tus datos', 'Estado de uñas', 'Tu servicio', 'Diseño', 'Cita'];
const timeSlots = ['11:00 AM','12:00 PM','1:00 PM','2:00 PM','3:00 PM','4:00 PM','5:00 PM','6:00 PM'];

function App(){
  const [view, setView] = useState('client');
  const [step, setStep] = useState(0);
  const [services, setServices] = useState(initialServices);
  const [form, setForm] = useState({ name:'', dni:'', phone:'', source:'Instagram', currentSystem:'Ningún sistema', days:'', condition:'No', sensitive:'No', category:'Manicura', service:'gel', extras:[], length:'Largo 1', shape:'Almendra', date:'', time:'', notes:'' });
  const [submitted, setSubmitted] = useState(false);
  const [clients, setClients] = useState([{id:1,name:'Camila Torres',phone:'987 654 321',visits:3,last:'12 Ago 2026',status:'Confirmada',service:'Rubber',artist:'Valeria',note:'Uñas saludables; próxima visita en 3 semanas.'},{id:2,name:'Andrea Rojas',phone:'934 118 500',visits:1,last:'Sin visitas anteriores',status:'Pendiente',service:'Gel color',artist:'Por asignar',note:''}]);
  const selected = services.find(x=>x.id===form.service);
  const total = (selected?.price||0) + form.extras.reduce((n,id)=>n+(extras.find(x=>x.id===id)?.price||0),0);
  const update = (field, value) => setForm(f=>({...f,[field]:value}));
  const toggleExtra = id => update('extras', form.extras.includes(id) ? form.extras.filter(x=>x!==id) : [...form.extras,id]);
  const submit = () => { setSubmitted(true); setClients(c=>[{id:Date.now(),name:form.name||'Nueva clienta',phone:form.phone,visits:0,last:'Nueva reserva',status:'Pendiente de confirmación',service:selected?.name,artist:'Por asignar',note:''},...c]); };
  return <div className="app">
    <header><div className="brand"><span>H</span><div>HARU <small>BEAUTY STUDIO</small></div></div><nav>{[['client','Reservar'],['artist','Artista'],['admin','Administración']].map(([id,label])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}>{label}</button>)}</nav></header>
    {view==='client' && <ClientWizard {...{step,setStep,form,update,services,selected,total,toggleExtra,submitted,setSubmitted,submit}} />}
    {view==='artist' && <ArtistDashboard clients={clients} setClients={setClients} />}
    {view==='admin' && <AdminDashboard services={services} setServices={setServices} />}
  </div>
}

function ClientWizard(p){
  const content = [
    <section className="fields" key="personal"><h1>Empecemos por conocerte ✨</h1><p>Usaremos estos datos para confirmar tu cita.</p><label>Nombres y apellidos completos *<input value={p.form.name} onChange={e=>p.update('name',e.target.value)} placeholder="Ej. Valentina Ruiz" /></label><div className="two"><label>DNI o C.E. *<input value={p.form.dni} onChange={e=>p.update('dni',e.target.value)} /></label><label>Número de celular *<input value={p.form.phone} onChange={e=>p.update('phone',e.target.value)} placeholder="999 999 999" /></label></div><label>¿Cómo nos conociste? *<select value={p.form.source} onChange={e=>p.update('source',e.target.value)}>{['TikTok','Instagram','Facebook','Recomendación'].map(x=><option key={x}>{x}</option>)}</select></label></section>,
    <section className="fields" key="health"><h1>Cuidemos tus uñas</h1><p>Esta información ayuda a recomendarte el sistema adecuado.</p><label>¿Tienes algún sistema actualmente? *<select value={p.form.currentSystem} onChange={e=>p.update('currentSystem',e.target.value)}>{['Gel color semipermanente','Soft gel','Rubber','Polygel','Acrílica','Builder','Esmalte tradicional','Ningún sistema'].map(x=><option key={x}>{x}</option>)}</select></label><label>¿Hace cuántos días lo realizaste?<input type="number" value={p.form.days} onChange={e=>p.update('days',e.target.value)} placeholder="Ej. 21" /></label><label>¿Cómo están tus uñas naturales? *<select value={p.form.condition} onChange={e=>p.update('condition',e.target.value)}>{['No','Sí, por morderlas','Sí, por retiro indebido de otro salón','Mis uñas naturales son débiles'].map(x=><option key={x}>{x}</option>)}</select></label><label>¿Sueles tener sensibilidad? *<div className="segmented">{['Sí','No'].map(x=><button className={p.form.sensitive===x?'selected':''} onClick={()=>p.update('sensitive',x)} key={x}>{x}</button>)}</div></label></section>,
    <section className="fields" key="service"><h1>Tu momento Haru</h1><p>Selecciona el servicio y el sistema que deseas.</p><div className="segmented">{['Manicura','Pedicura','Manicura y pedicura'].map(x=><button className={p.form.category===x?'selected':''} onClick={()=>p.update('category',x)} key={x}>{x}</button>)}</div><div className="service-grid">{p.services.map(s=><button key={s.id} className={'service '+(p.form.service===s.id?'selected':'')} onClick={()=>p.update('service',s.id)}><strong>{s.name}</strong><span>Desde S/{s.price} · {s.duration} min</span></button>)}</div><h3>Extras</h3>{extras.map(e=><label className="check" key={e.id}><input type="checkbox" checked={p.form.extras.includes(e.id)} onChange={()=>p.toggleExtra(e.id)} /> {e.name}<b>+ S/{e.price}</b></label>)}</section>,
    <section className="fields" key="design"><h1>El diseño que imaginas</h1><p>Sube una referencia; así podremos cotizar mejor tu cita.</p><label className="upload">＋ <strong>Subir foto de tus uñas actuales</strong><small>JPG o PNG, máximo 10 MB</small><input type="file" accept="image/*" /></label><label className="upload">＋ <strong>Subir foto de diseño de referencia</strong><small>JPG o PNG, máximo 10 MB</small><input type="file" accept="image/*" /></label><h3>¿Qué largo deseas?</h3><div className="segmented">{['Largo 1','Largo 2','Largo 3','Largo 4','Largo 5'].map(x=><button className={p.form.length===x?'selected':''} onClick={()=>p.update('length',x)} key={x}>{x}</button>)}</div><h3>Tipo de punta</h3><div className="segmented">{['Almendra','Coffin','Cuadrada','Stiletto','Redonda'].map(x=><button className={p.form.shape===x?'selected':''} onClick={()=>p.update('shape',x)} key={x}>{x}</button>)}</div></section>,
    <section className="fields" key="booking"><h1>Agenda tu cita</h1><p>Atendemos de lunes a sábado, de 11 AM a 8 PM.</p><div className="two"><label>Fecha que deseas *<input type="date" value={p.form.date} onChange={e=>p.update('date',e.target.value)} /></label><label>Hora *<select value={p.form.time} onChange={e=>p.update('time',e.target.value)}><option value="">Selecciona</option>{timeSlots.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Notas para tu cita<textarea value={p.form.notes} onChange={e=>p.update('notes',e.target.value)} placeholder="Cuéntanos algo que debamos saber…" /></label><aside className="estimate"><span>Cotización estimada</span><strong>S/{p.total}</strong><small>La confirmación final depende del diagnóstico y diseño.</small></aside><p className="fine">Luego de confirmar disponibilidad tendrás 5 minutos para abonar S/30 por Yape o transferencia.</p></section>
  ][p.step];
  if(p.submitted) return <main className="success"><div className="success-mark">✓</div><h1>¡Solicitud recibida!</h1><p>Revisaremos la disponibilidad y te escribiremos por WhatsApp para confirmar tu cita y cotización.</p><button onClick={()=>{p.setSubmitted(false);p.setStep(0)}}>Hacer otra reserva</button></main>;
  return <main className="wizard"><div className="progress">{steps.map((s,i)=><div className={i<=p.step?'done':''} key={s}><i>{i+1}</i><span>{s}</span></div>)}</div><div className="card">{content}<footer><button className="ghost" disabled={p.step===0} onClick={()=>p.setStep(x=>x-1)}>Atrás</button>{p.step===4?<button onClick={p.submit}>Enviar solicitud</button>:<button onClick={()=>p.setStep(x=>x+1)}>Continuar</button>}</footer></div><div className="booking-summary"><span>Tu selección</span><b>{p.selected?.name}</b><strong>S/{p.total}</strong></div></main>;
}

function ArtistDashboard({clients,setClients}){ const [selected,setSelected]=useState(clients[0]); const [note,setNote]=useState(''); return <main className="dashboard"><div><p className="eyebrow">PANEL DE ARTISTA</p><h1>Agenda y seguimiento</h1><p>Registra el resultado de cada servicio para cuidar mejor a tus clientas.</p></div><div className="dashboard-grid"><section className="card client-list"><h2>Clientas</h2>{clients.map(c=><button className={selected?.id===c.id?'selected':''} onClick={()=>setSelected(c)} key={c.id}><strong>{c.name}</strong><span>{c.status} · {c.service}</span></button>)}</section>{selected&&<section className="card client-record"><div className="record-title"><div><p className="eyebrow">FICHA DE CLIENTA</p><h2>{selected.name}</h2><p>{selected.phone} · {selected.visits} visita{selected.visits!==1?'s':''}</p></div><span className={'pill '+selected.status.toLowerCase().replaceAll(' ','-')}>{selected.status}</span></div><div className="history"><div><small>Última cita</small><b>{selected.last}</b></div><div><small>Servicio</small><b>{selected.service}</b></div><div><small>Artista</small><b>{selected.artist}</b></div></div><h3>Seguimiento clínico/estético</h3><p className="note">{selected.note || 'Aún no hay una nota de seguimiento.'}</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Ej. Uñas saludables, sellado correcto; recomendar retorno en 3 semanas."/><button onClick={()=>{setClients(cs=>cs.map(c=>c.id===selected.id?{...c,note,status:'Atendida',visits:Math.max(1,c.visits)}:c));setSelected({...selected,note,status:'Atendida'});setNote('')}}>Guardar resultado de cita</button></section>}</div></main> }
function AdminDashboard({services,setServices}){ const [newName,setNewName]=useState(''); const [newPrice,setNewPrice]=useState(''); return <main className="dashboard"><div><p className="eyebrow">ADMINISTRACIÓN</p><h1>Configuración de Haru</h1><p>Edita la oferta sin depender de desarrollo.</p></div><section className="card admin"><h2>Servicios, precios y duración</h2><div className="service-table"><div className="table-head"><span>Servicio</span><span>Desde</span><span>Duración</span></div>{services.map(s=><div className="table-row" key={s.id}><span>{s.name}</span><label>S/<input type="number" value={s.price} onChange={e=>setServices(xs=>xs.map(x=>x.id===s.id?{...x,price:+e.target.value}:x))}/></label><label><input type="number" value={s.duration} onChange={e=>setServices(xs=>xs.map(x=>x.id===s.id?{...x,duration:+e.target.value}:x))}/> min</label></div>)}</div><h3>Nuevo servicio</h3><div className="new-service"><input placeholder="Nombre del servicio" value={newName} onChange={e=>setNewName(e.target.value)}/><input type="number" placeholder="Precio" value={newPrice} onChange={e=>setNewPrice(e.target.value)}/><button onClick={()=>{if(newName&&newPrice){setServices(s=>[...s,{id:Date.now().toString(),name:newName,price:+newPrice,duration:120}]);setNewName('');setNewPrice('')}}}>Agregar</button></div></section><section className="card settings"><h2>Reglas de agenda</h2><p>Horario: lunes a sábado, 11:00 AM – 8:00 PM</p><button className="ghost">Gestionar feriados</button><button className="ghost">Gestionar artistas</button><button className="ghost">Editar preguntas del wizard</button></section></main> }
createRoot(document.getElementById('root')).render(<App/>);
